OKE - handle VZ failure

diff --git a/.github/workflows/github-actions-demo.yml b/.github/workflows/github-actions-demo.yml
--- a/.github/workflows/github-actions-demo.yml
+++ b/.github/workflows/github-actions-demo.yml
@@ -504,7 +504,7 @@ jobs:
           echo "wait_time: $wait_time"
           echo "vz_state: $VZ_STATE"
           
-          while [[ "${VZ_STATE}" != "InstallComplete" || "${VZ_STATE}" != "InstallFailed" ]];
+          while [[ "${VZ_STATE}" != "InstallComplete" ]];
           do
               if [ $(date -u +%s) -gt $wait_time ];
               then
@@ -516,19 +516,20 @@ jobs:
               kubectl get verrazzano
               VZ_STATE=$(kubectl get verrazzano | grep letsencrypt-certs-example | awk {'print $2'})
               echo "VZ_STATE=${VZ_STATE}" >> $GITHUB_ENV
+
+              if [ "${VZ_STATE}" == "InstallFailed" ];
+              then
+                echo "Verrazzano installation failed!"
+                kubectl logs -f $(kubectl get pods | grep verrazzano-install |  awk {'print $1'})
+                exit 1
+              fi
+              
           done
 
           echo "=================================================="
           echo "Verrazzano installation completed!"
           kubectl get verrazzano
           echo "=================================================="
-
-          if [ "${VZ_STATE}" == "InstallFailed" ];
-          then
-            echo "Verrazzano installation failed!"
-            kubectl logs -f $(kubectl get pods | grep verrazzano-install |  awk {'print $1'})
-            exit 1
-          fi
           
           echo "Get console URLs"
           kubectl get vz -o jsonpath="{.items[].status.instance}" | jq .
